import React, { useState, useEffect } from 'react';
import api from '../../services/api';
import { Calendar, Clock, MapPin, Sparkles, Star, Download } from 'lucide-react';
import Card from '../../components/common/Card';
import Badge from '../../components/common/Badge';
import Button from '../../components/common/Button';
import PageHeader from '../../components/common/PageHeader';

export default function StudentTimetableView() {
  const [timetable, setTimetable] = useState([
    {
      id: 'slot-1',
      date: 'Dec 10, 2026',
      day: 'Thursday',
      subjectCode: 'CSE3001',
      subjectName: 'Database Management Systems',
      time: '09:00 AM - 12:00 PM',
      room: 'A101',
      building: 'Main Block',
      seatNumber: 'Desk A-14',
      isNext: true
    },
    {
      id: 'slot-2',
      date: 'Dec 10, 2026',
      day: 'Thursday',
      subjectCode: 'CSE3002',
      subjectName: 'Operating Systems',
      time: '02:00 PM - 05:00 PM',
      room: 'A102',
      building: 'Main Block',
      seatNumber: 'Desk B-08',
      isNext: false
    },
    {
      id: 'slot-3',
      date: 'Dec 11, 2026',
      day: 'Friday',
      subjectCode: 'CSE3003',
      subjectName: 'Computer Networks',
      time: '09:00 AM - 12:00 PM',
      room: 'A201',
      building: 'Main Block',
      seatNumber: 'Desk C-22',
      isNext: false
    },
    {
      id: 'slot-4',
      date: 'Dec 12, 2026',
      day: 'Saturday',
      subjectCode: 'CSE3004',
      subjectName: 'Software Engineering & GA',
      time: '09:00 AM - 12:00 PM',
      room: 'A101',
      building: 'Main Block',
      seatNumber: 'Desk A-14',
      isNext: false
    }
  ]);

  const nextExam = timetable.find(t => t.isNext) || timetable[0];

  return (
    <div className="space-y-6">
      <PageHeader
        title="My Examination Timetable Matrix"
        subtitle="Conflict-free examination timetable generated by Genetic Algorithm engine"
      />

      {/* Next Examination Spotlight Banner */}
      {nextExam && (
        <div className="p-6 rounded-3xl bg-gradient-to-r from-blue-50 via-white to-sky-50 border border-blue-200 shadow-sm relative overflow-hidden flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full text-xs font-bold bg-cyan-500/10 text-cyan-700 border border-cyan-500/30">
              <Star className="w-3.5 h-3.5 fill-current text-amber-700" />
              <span>Next Upcoming Examination</span>
            </div>
            <h2 className="text-xl md:text-2xl font-black text-slate-900 font-manrope">
              {nextExam.subjectCode} — {nextExam.subjectName}
            </h2>
            <div className="flex flex-wrap items-center gap-4 text-xs text-slate-700 pt-1">
              <div className="flex items-center space-x-1.5">
                <Calendar className="w-4 h-4 text-cyan-700" />
                <span>{nextExam.date} ({nextExam.day})</span>
              </div>
              <div className="flex items-center space-x-1.5">
                <Clock className="w-4 h-4 text-indigo-600" />
                <span>{nextExam.time}</span>
              </div>
              <div className="flex items-center space-x-1.5">
                <MapPin className="w-4 h-4 text-emerald-700" />
                <span>Room {nextExam.room}, {nextExam.building}</span>
              </div>
            </div>
          </div>

          <Badge variant="warning" size="lg" className="self-start md:self-center font-mono">
            {nextExam.seatNumber}
          </Badge>
        </div>
      )}

      {/* Timetable Table */}
      <Card className="p-6">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-[#F3F7FE] border-b border-slate-200 text-slate-600 uppercase tracking-wider">
              <tr>
                <th className="px-4 py-3">Date</th>
                <th className="px-4 py-3">Day</th>
                <th className="px-4 py-3">Subject Code</th>
                <th className="px-4 py-3">Subject Title</th>
                <th className="px-4 py-3">Session Time</th>
                <th className="px-4 py-3">Room</th>
                <th className="px-4 py-3">Building</th>
                <th className="px-4 py-3 text-right">Desk Seat</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-mono">
              {timetable.map((row) => (
                <tr 
                  key={row.id} 
                  className={`transition ${row.isNext ? 'bg-cyan-500/10 border-l-4 border-cyan-400' : 'hover:bg-[#F3F7FE]/60'}`}
                >
                  <td className="px-4 py-3.5 text-slate-800 font-semibold font-sans">
                    {row.date}
                  </td>
                  <td className="px-4 py-3.5 text-slate-600 font-sans">
                    {row.day}
                  </td>
                  <td className="px-4 py-3.5 font-bold text-cyan-700">
                    {row.subjectCode}
                  </td>
                  <td className="px-4 py-3.5 text-slate-900 font-semibold font-sans">
                    {row.subjectName}
                  </td>
                  <td className="px-4 py-3.5 text-indigo-700 font-sans">
                    {row.time}
                  </td>
                  <td className="px-4 py-3.5 text-emerald-700 font-bold">
                    {row.room}
                  </td>
                  <td className="px-4 py-3.5 text-slate-600 font-sans">
                    {row.building}
                  </td>
                  <td className="px-4 py-3.5 text-right font-bold text-amber-700">
                    {row.seatNumber}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
